const notificationRecipients = [
  {
    id: 'classroom-teacher',
    name: 'Jordan Classroom Teacher',
    email: 'classroom.teacher@school.edu',
    phone: '+61400000011',
    role: 'classroom_teacher',
    active: true,
  },
  {
    id: 'leading-teacher',
    name: 'Taylor Leading Teacher',
    email: 'leading.teacher@school.edu',
    phone: '+61400000012',
    role: 'leading_teacher',
    active: true,
  },
  {
    id: 'first-aid-officer',
    name: 'Casey First Aid Officer',
    email: 'firstaid@school.edu',
    phone: '+61400000013',
    role: 'first_aid_officer',
    active: true,
  },
  {
    id: 'student-services',
    name: 'Alex Student Services',
    email: 'studentservices@school.edu',
    phone: '+61400000014',
    role: 'student_services',
    active: true,
  },
  {
    id: 'assistant-principal',
    name: 'Morgan Assistant Principal',
    email: 'assistant.principal@school.edu',
    phone: '+61400000015',
    role: 'assistant_principal',
    active: true,
  },
  {
    id: 'principal',
    name: 'Riley Principal',
    email: 'principal@school.edu',
    phone: '+61400000016',
    role: 'principal',
    active: true,
  },
  {
    id: 'maintenance-facilities',
    name: 'Sam Facilities Lead',
    email: 'facilities@school.edu',
    phone: '+61400000017',
    role: 'maintenance_facilities',
    active: true,
  },
  {
    id: 'relevant-staff',
    name: 'Jamie Relevant Staff',
    email: 'relevant.staff@school.edu',
    phone: '+61400000018',
    role: 'relevant_staff',
    active: true,
  },
]

const notificationRouting = [
  {
    id: 'emergency-natural-disaster',
    alertScope: 'emergency',
    alertType: 'Natural Disaster',
    priority: 'critical',
    channels: ['sms', 'email'],
    roles: ['principal', 'assistant_principal', 'leading_teacher', 'first_aid_officer'],
    active: true,
  },
  {
    id: 'emergency-fire',
    alertScope: 'emergency',
    alertType: 'Fire',
    priority: 'critical',
    channels: ['sms', 'email'],
    roles: ['principal', 'assistant_principal', 'leading_teacher', 'first_aid_officer'],
    active: true,
  },
  {
    id: 'emergency-threat',
    alertScope: 'emergency',
    alertType: 'Threat',
    priority: 'critical',
    channels: ['sms', 'email'],
    roles: ['principal', 'assistant_principal', 'leading_teacher', 'first_aid_officer'],
    active: true,
  },
  {
    id: 'general-medical',
    alertScope: 'general',
    alertType: 'medical',
    priority: 'high',
    channels: ['sms', 'email'],
    roles: ['first_aid_officer', 'student_services', 'leading_teacher'],
    active: true,
  },
  {
    id: 'general-fire',
    alertScope: 'general',
    alertType: 'fire',
    priority: 'medium',
    channels: ['email'],
    roles: ['leading_teacher', 'assistant_principal'],
    active: true,
  },
  {
    id: 'general-lockdown',
    alertScope: 'general',
    alertType: 'lockdown',
    priority: 'critical',
    channels: ['sms', 'email'],
    roles: ['principal', 'assistant_principal', 'leading_teacher', 'classroom_teacher'],
    active: true,
  },
  {
    id: 'general-behaviour',
    alertScope: 'general',
    alertType: 'behaviour',
    priority: 'medium',
    channels: ['email'],
    roles: ['leading_teacher', 'student_services'],
    active: true,
  },
  {
    id: 'general-weather',
    alertScope: 'general',
    alertType: 'weather',
    priority: 'medium',
    channels: ['email'],
    roles: ['relevant_staff'],
    active: true,
  },
  {
    id: 'general-maintenance',
    alertScope: 'general',
    alertType: 'maintenance',
    priority: 'low',
    channels: ['email'],
    roles: ['relevant_staff'],
    active: true,
  },
  {
    id: 'general-general',
    alertScope: 'general',
    alertType: 'general',
    priority: 'low',
    channels: ['email'],
    roles: ['relevant_staff'],
    active: true,
  },
]

module.exports = { notificationRecipients, notificationRouting }
